import { test, expect } from '@playwright/test';

test.describe('FrameFlux real-user end-to-end flow', () => {
  test('landing → signup → dashboard → upload → editor → tools → export dialog', async ({ page }) => {
    const email = `qa_${Date.now()}@example.com`;
    const password = 'TestPass123!';

    // Landing page
    await page.goto('/');
    await expect(page).toHaveTitle(/FrameFlux/i);
    await expect(page.getByRole('link', { name: /frameflux/i }).first()).toBeVisible();

    // Signup
    await page.goto('/auth/signup');
    await expect(page.getByRole('heading', { name: /create your account/i })).toBeVisible();
    await page.getByLabel(/full name/i).fill('QA Browser User');
    await page.getByLabel(/email/i).fill(email);
    await page.getByLabel(/password/i).fill(password);
    await page.getByRole('button', { name: /create account/i }).click();
    await page.waitForURL(/\/app\/dashboard$/, { timeout: 60_000 });
    await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible();

    // Dashboard
    await page.goto('/app/dashboard/media');
    await expect(page.getByRole('heading', { name: 'Media' })).toBeVisible();
    await expect(page.getByRole('button', { name: /upload media/i })).toBeVisible();

    // Upload a tiny deterministic MP4 generated by the workflow
    await page.getByRole('button', { name: /upload media/i }).click();
    const chooserPromise = page.waitForEvent('filechooser');
    await page.getByText(/drag & drop a file here/i).click();
    const chooser = await chooserPromise;
    await chooser.setFiles('e2e/fixtures/sample.mp4');
    await expect(page.getByText('sample.mp4', { exact: true }).first()).toBeVisible();
    await page.getByRole('button', { name: /^upload$/i }).click();

    await page.waitForURL(/\/app\/dashboard\/media\/[^/?]+\?from_upload=1$/, { timeout: 120_000 });
    await expect(page.getByText(/media uploaded successfully/i)).toBeVisible();

    // Editor core controls
    await expect(page.getByRole('button', { name: /^export$/i }).first()).toBeVisible();
    await expect(page.getByRole('button', { name: /play/i }).first()).toBeVisible();
    await expect(page.getByRole('button', { name: /skip back/i }).first()).toBeVisible();
    await expect(page.getByRole('button', { name: /skip forward/i }).first()).toBeVisible();

    // Exercise every primary editor tab.
    const tabs = [
      { name: 'Edit', marker: /split|delete|trim/i },
      { name: 'Audio', marker: /audio/i },
      { name: 'Subs', marker: /subtitle|subtitles|caption/i },
      { name: 'Transform', marker: /transform|scale|rotate|crop|speed/i },
      { name: 'Overlay', marker: /overlay|text|watermark/i },
    ];

    for (const tab of tabs) {
      await page.getByRole('button', { name: new RegExp(`^${tab.name}$`, 'i') }).click();
      await expect(page.getByText(tab.marker).first()).toBeVisible();
    }

    // Playback interaction
    const video = page.locator('video').first();
    await expect(video).toBeVisible();
    await page.getByRole('button', { name: /play/i }).first().click();
    await page.waitForTimeout(750);
    await page.getByRole('button', { name: /pause/i }).first().click();

    // Export dialog open/close and option interaction
    await page.getByRole('button', { name: /^export$/i }).first().click();
    await expect(page.getByRole('heading', { name: /export settings/i })).toBeVisible();
    await expect(page.getByText('Output Format')).toBeVisible();
    await expect(page.getByText('Resolution Preset').first()).toBeVisible({ timeout: 15_000 }).catch(() => {});
    await page.getByRole('button', { name: /cancel/i }).click();
    await expect(page.getByRole('heading', { name: /export settings/i })).toHaveCount(0);
  });
});
